-- V1__Create_Trafego_Table.sql
CREATE SEQUENCE SEQ_TRAFEGO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE TABLE TBL_TRAFEGO (
    ID INTEGER DEFAULT SEQ_TRAFEGO.NEXTVAL NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    VELOCIDADE INTEGER NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL
);
