-- V2__Create_Semaforo_Table.sql
CREATE SEQUENCE SEQ_SEMAFORO
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

CREATE TABLE TBL_SEMAFORO (
     ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     STATUS VARCHAR(20) NOT NULL,
     LOCALIZACAO VARCHAR(100) NOT NULL,
     ULTIMA_ATUALIZACAO TIMESTAMP NOT NULL
);