-- V3__Create_Emergencias_Table.sql
CREATE SEQUENCE SEQ_EMERGENCIAS
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;



CREATE TABLE TBL_EMERGENCIAS (
     ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     TIPO VARCHAR(50) NOT NULL,
     LOCALIZACAO VARCHAR(100) NOT NULL,
     DESCRICAO VARCHAR(255),
     DATA_HORA TIMESTAMP NOT NULL
);