-- V4__Create_Rotas_Table.sql
CREATE SEQUENCE SEQ_ROTAS
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;


CREATE TABLE TBL_ROTAS (
     ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     ORIGEM VARCHAR(100) NOT NULL,
     DESTINO VARCHAR(100) NOT NULL,
     DISTANCIA_KM DECIMAL(10,2) NOT NULL,
     DURACAO_MINUTOS INTEGER NOT NULL
);
