-- V5__Create_Veiculos_Table.sql
CREATE SEQUENCE SEQ_VEICULOS
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;


CREATE TABLE TBL_VEICULOS (
     ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     MODELO VARCHAR(100) NOT NULL,
     PLACA VARCHAR(10) NOT NULL,
     ANO INTEGER NOT NULL,
     COR VARCHAR(20),
     ULTIMA_MANUTENCAO DATE
);